name: Deploy Application Stack

on:
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:
  workflow_call:

run-name: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.message || github.event.head_commit.message }}

jobs:
  deploy:
    name: Deploy Application Stack
    runs-on: ubuntu-latest

    steps:
      - name: Update Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOYMENT_SSH_HOST }}
          port: ${{ secrets.DEPLOYMENT_SSH_PORT }}
          username: ${{ secrets.DEPLOYMENT_SSH_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY }}
          script: |
            cd ~/services/starpep-web/
            docker compose rm -fs
            git pull
            docker compose pull
            docker compose up -d
