name: Deploy Application Stack

on:
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:
  workflow_call:

run-name: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.message || github.event.head_commit.message }}

jobs:
  deploy:
    name: Deploy Application Stack
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo "DEPLOY"
